# USB + BLE (you’ll use wired, but BLE stays enabled)
CONFIG_ZMK_USB=y
CONFIG_ZMK_BLE=y

# OLED (SSD1306 128x32)
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=y

# Keep awake while testing
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=0

